### ISSUE TITLE
Undefined variables?

### ISSUE THREAD

**Issue by akashrpatel** [chrisiaut/influxdb_radius_analyzer#1]
Hello Christian,

I am attempting to setup a demo as you described on your blog.

I've completed everything up to testing go the script to get data into influx. When I run the analyze_influx.php file, I receive the following errors and only entry in my influxdb "radius".

Any assistance would be greatly appreciated. 

 Undefined variable: requests in C:\influxdb_radius_analyzer-master\analyze_influx.php on line 131
 Undefined offset: 1 in C:\influxdb_radius_analyzer-master\analyze_influx.php on line 134
 Undefined variable: OU in C:\influxdb_radius_analyzer-master\analyze_influx.php on line 144

Thank you,
Akash

**Comment by geek-at** [comment]
Looks like the log format can't be parsed. Did you check if your log format from the NPS server is set to "ODBC (legacy)"?

Configure the NPS logging (NPS -> Accounting -> Logging settings) to save in the format ODBC (Legacy) and "Monthly"

**Comment by akashrpatel** [comment]
Thank you for your response.

I did configure it for ODBC (Legacy) - Monthly, just double checked.

**Comment by geek-at** [comment]
okay and there is no data in the database? Because those warnings and notices should not be critical and it should still work.

If there is no data in the database you have to check if there is a query problem. You can do this by 'tail -f' the influxdb log file. On debian it would be 

`tail -f /var/log/influxdb/influxd.log`

I have seen problems with spaces in the queries. Let me know if you see any errors

**Comment by geek-at** [comment]
should be fixed with the ned update
